# Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: book-catalog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: book-catalog
  template:
    metadata:
      labels:
        app: book-catalog
    spec:
      containers:
      - name: book-catalog
        image: week081:1
        imagePullPolicy: Never
        env:
        - name: DATABASE_URL
          value: "postgresql://week08_idrq_user:K0TF4FhqQWPcYbb3YrdnvGoqU7p74RpW@dpg-crifrqdumphs73cjnl7g-a.oregon-postgres.render.com/week08_idrq"
        command: ["uvicorn"]
        args: ["main:app", "--host", "0.0.0.0", "--port", "8000"]
---
# Service
apiVersion: v1
kind: Service
metadata:
  name: book-catalog
spec:
  selector:
    app: book-catalog
  type: NodePort
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000
    nodePort: 30001
